apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: 'trace_id'
          matcherType: label
          name: trace_id
          url: '$${__value.raw}'
          urlDisplayLabel: 'View Trace'

        - datasourceUid: tempo
          matcherRegex: 'span_id'
          matcherType: label
          name: span_id
          url: "{span:id=\"$${__value.raw}\"}"
          urlDisplayLabel: 'View Span'  
    

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: 'loki'
        spanStartTimeShift: '-1h'
        spanEndTimeShift: '1h'
        tags: 
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: "{$${__tags}}|trace_id=\"$${__trace.traceId}\"|span_id=\"$${__span.spanId}\"" 
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: 'mimir'      

  - name: Mimir
    type: prometheus
    uid: mimir
    editable: true
    access: proxy
    url: http://mimir:9009/prometheus
    jsonData:
        httpMethod: GET
