auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

distributor:
  otlp_config:
    default_resource_attributes_as_index_labels:
      - service.name
      - service.instance.id
      - host.name
      - host.arch

ruler:
  alertmanager_url: http://loki:9093

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 30d
